// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tgskooykhahtokhmtwev.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRnc2tvb3lraGFodG9raG10d2V2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1MTUyNDcsImV4cCI6MjA2MjA5MTI0N30.2pIMgkvLxYKhZD_1M4B70--14ugkb-x_wIo2_nLILRc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);